# Generated by Django 5.1.2 on 2024-10-22 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_HernandezVivas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='edad',
        ),
    ]
